---
# Basic cerver configuration
- name: Enable hostname persistence
  lineinfile:
    backup: yes
    dest: "/etc/cloud/cloud.cfg"
    state: present
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.release is version('18.04', '>=')

- name: Set Hostname
  hostname:
      name: "{{ base_hostname|default(inventory_hostname) }}"

- name: Set Hosts base entry
  template:
      dest: /etc/hosts
      src: hosts_file
      owner: root
      group: root
      mode: 0644

- name: Enable locales
  template:
    src: enabled_locales
    dest: /etc/locale.gen
    mode: 0644
    owner: root
    group: root
  notify: Generate locales

- name: Set locale
  template:
      src: default_locale
      dest: /etc/default/locale
      mode: 0644
      owner: root
      group: root

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Set motd
  copy:
    src: "{{ base_motd }}"
    dest: /etc/motd
  when: base_motd is defined

- name: Set fstab
  copy:
    src: "{{ base_fstab }}"
    dest: /etc/fstab
  when: base_fstab is defined

- name: Set repositories
  template:
    src: sources
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
  when: ansible_lsb.id == "Ubuntu"

- name: Update package list
  apt:
    update_cache: yes
  when: ansible_lsb.id == "Ubuntu"
