---
# Basic cerver configuration

- name: Set Hostname
  hostname:
      name: "{{ inventory_hostname  }}"

- name: Set Hosts base entry
  template:
      dest: /etc/hosts
      src: hosts_file
      owner: root
      group: root
      mode: 0644

- name: Enable locales
  template:
    src: enabled_locales
    dest: /etc/locale.gen
    mode: 0644
    owner: root
    group: root
  notify: Generate locales

- name: Set locale
  template:
      src: default_locale
      dest: /etc/default/locale
      mode: 0644
      owner: root
      group: root

- name: Set timezone
  command: "timedatectl set-timezone {{ timezone }}"

- name: Set motd
  copy:
    src: "{{ base_motd }}"
    dest: /etc/motd
  when: base_motd is defined

- name: Set fstab
  copy:
    src: "{{ base_fstab }}"
    dest: /etc/fstab
  when: base_fstab is defined
