- name: Install Requirements - Archlinux
  pacman:
    name: "{{ base_dependencies_arch|default(omit) }}"
    state: latest
    update_cache: yes

- name: Install Optional Requirements - Archlinux
  pacman:
    name: "{{ base_optional_dependencies_arch|default(omit) }}"
    state: latest
    update_cache: yes
  when:
    - base_optional_dependencies_arch is defined
