---

- name: Remove old network manager
  apt:
    name: ifupdown
    state: absent

- name: Install netplan
  apt:
    name: netplan.io
    state: present

- name: Remove default network configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/netplan/01-netcfg.yaml"
    - "/etc/netplan/50-cloud-init.yaml"
    - "/etc/netplan/01-network-manager-all.yaml"

- name: Configure network interfaces - dynamic
  template:
    src: netplan
    dest: /etc/netplan/01-ansible.yaml
    owner: root
    group: root
  when: not base_network_config_static
  notify:
    - Netplan generate

- name: Configure network interfaces - static
  copy:
    src: "{{ item }}"
    dest: /etc/netplan/01-ansible.yaml
    owner: root
    group: root
  when: base_network_config_static
  with_fileglob: "{{ conf_dir }}/etc/netplan/*"
  notify:
    - Netplan generate
