---
# Setup ntp


- name: Install ntp - Ubuntu
  apt:
      name: "ntpd"
      state: latest
      force: yes
  notify: Restart ntp
  when: ansible_os_family == "ansible_distribution"

- name: Configure ntp
  template:
      backup: yes
      mode: 0644
      owner: root
      group: root
      src: "ntp_config"
      dest: "/etc/ntp.conf"
  notify: Restart ntp

- name: Allow NTP
  ufw:
    port: 123
    proto: udp
    rule: allow
    from_ip: "{{ item }}"
  when: base_ntp_open
  with_items: "{{ base_ntp_open_to_address|default(omit) }}"
