---
#Setup SSH

- name: Install ssh - Ubuntu
  apt:
      name: "openssh-server"
      state: latest
      force: yes
  when: ansible_os_family == "Debian"

- name: Install ssh - Archlinux
  pacman:
      name: "openssh"
      state: latest
  when: ansible_os_family == "Archlinux"

- name: Configure ssh
  template:
      src: "sshd_config"
      dest: "/etc/ssh/sshd_config"
      mode: 0644
      owner: root
      group: root
  notify: Restart ssh
