---
# Ufw tasks
- name: Install ufw
  apt:
    name: ufw
    state: latest
    force: yes
  notify:
  - Restart ufw

- name: Allow SSH
  ufw:
    port: "{{ ssh_port }}"
    proto: tcp
    rule: allow

- name: Allow public ports
  ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    rule: allow
  with_items: "{{ ufw_allowed_public_ports }}"
  when: ufw_allowed_public_ports is defined

- name: Set default policy
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Start ufw
  service:
    name: ufw
    state: started
    enabled: yes
