---
# Ufw install tasks
- include: ufw_install_ubuntu.yml
  when: ansible_os_family == "Debian"
- include: ufw_install_archlinux.yml
  when: ansible_os_family == "Archlinux"
- include: ufw_install_centos.yml
  when: ansible_os_family == "RedHat"

# Ufw configuration
- name: Allow SSH
  ufw:
    port: "{{ ssh_port }}"
    proto: tcp
    rule: allow

- name: Allow public ports
  ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.from|default('')}}"
    rule: allow
  with_items: "{{ ufw_allowed_public_ports|default(omit) }}"
  when: ufw_allowed_public_ports is defined

- name: Allow local ports
  ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from: "{{ item.from }}"
    rule: allow
  with_items: "{{ ufw_allowed_local_ports|default(omit) }}"
  when: ufw_allowed_local_ports is defined

- name: Set default policy
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Start ufw
  service:
    name: ufw
    state: started
    enabled: yes
