---
#Add users task

- name: Add admin group
  group:
      name: "{{ base_admin_group }}"
      state: present
      system: yes

- name: Make sudo conf.d directory
  file:
    path: /etc/sudoers.d
    state: directory

- name: Add admin group to sudo
  template:
      src: admin_group_passwordless_sudo
      dest: /etc/sudoers.d/base_admin_group_passwordless_sudo
      owner: root
      group: root
      mode: 0400

- name: Add admin users
  user:
      name: "{{ item }}"
      state: present
      shell: /bin/bash
      groups: "{{ base_admin_group }}"
  loop: "{{ [ admin_accounts|default(omit), admin_accounts_local ] | flatten(levels=1) }}"
  when: admin_accounts is defined or admin_accounts_local is defined

- name: Add normal users
  user:
      name: "{{ item }}"
      state: present
      shell: /bin/bash
  loop: "{{ [ user_accounts|default(omit), user_accounts_local ] | flatten(levels=1) }}"
  when: user_accounts is defined or user_accounts_local is defined

- name: Add admin authorized keys
  authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', base_users_dirs+'/'+item+'/.ssh/id_rsa.pub') }}"
      state: present
  loop: "{{ [ admin_accounts|default(omit), admin_accounts_local ] | flatten(levels=1) }}"
  when: admin_accounts is defined or admin_accounts_local is defined

- name: Add user authorized keys
  authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', base_users_dirs+'/'+item+'/.ssh/id_rsa.pub') }}"
      state: present
  loop: "{{ [ admin_accounts|default(omit), admin_accounts_local ] | flatten(levels=1) }}"
  when: admin_accounts is defined or admin_accounts_local is defined
